### ISSUE TITLE
Blocks placed with context lack contextual editing hover links and markup.

### ISSUE THREAD

**Issue by gstout** [oddhill/context#31]
Blocks placed with context lack Contextual editing hover links and markup. (The little gears.) :)

**Comment by NormySan** [comment]
@gstout This is because the blocks can not be directly edited like regular Drupal blocks since they are not entities. They have to be edited through the Context UI.

**Comment by NormySan** [comment]
I'm closing this issue, see my previous comment above about the issue.

It might be possible to somehow integrate this with the contextual editing system and be directed to the context page.

If someone feels like taking this on please open a new issue or do a pull-request with the changes.
